### ISSUE TITLE
Stale link

### ISSUE THREAD

**Issue by BillieB0B** [plembo/onemoretech#1]
Newbie in GitHub so trying this.....the link https://jantore.net/hardware/rooting-zyxel-gs1900/ does not work. Would you have saved the content of the link to publish here please? I have searched for it elsewhere with not luck.
Thank you

**Comment by plembo** [comment]
I didn't keep a copy, but was able to find it on the Wayback Machine:


https://web.archive.org/web/20170203145910/https://jantore.net/hardware/rooting-zyxel-gs1900/

**Comment by plembo** [comment]
Think that solves it.
